# Lab1: Reviewing Jupyter Notebook and Python; Learning Pandas

Welcome to Pyschology 101D: Data Science for Psychology!  Each week you will complete a lab assignment like this one.  You can't learn technical subjects without hands-on practice, so labs are an important part of the course.

Before we get started, there are some administrative details.

Labs are required. There are two ways to receive credit for each lab.

1. (The normal way) Come to your lab section and work on the lab as directed. Before you leave, you need to submit the lab **and** have a staff member check you off to confirm that you came to lab section and attempted to make progress while you were there. You do not need to finish the lab or answer every question correctly to receive full credit. However, you do need to try; that's why we check you off. Expect to discuss your progress briefly with a staff member before they will check you off.
    
2. (The hard way) Lab assignments will be posted Monday night. If you complete the entire lab so that all tests pass and submit it by 11:59pm on Tuesday, then you don't need to physically attend lab for the rest of the week.

Collaborating on labs is more than okay -- it's encouraged! You should rarely be stuck for more than a few minutes on questions in labs, so ask a neighbor or an instructor for help. (Explaining things is beneficial, too -- the best way to solidify your knowledge of a subject is to explain it.) Please don't just share answers, though.

You can read more about [course policies](http://data8.org/su17/policies.html) on the [course website](http://data8.org/su17).

#### Today's lab

In today's lab, you'll learn how to:

1. gain a better understanding (or even mastery) of Jupyter notebooks,
2. refamiliarize yourself with Python,
2. learn how to use the Pandas module.

This lab covers parts of [Chapter 3](http://www.inferentialthinking.com/chapters/03/programming-in-python.html) of the online textbook. You should read the book, but not right now. Instead, let's get started!

#### Joke of the day:

Why do assembly programmers need to know how to swim?

Because they work below C level.

In [ ]:
# Importing standard data science libraries
import numpy as np
import pandas as pd

# 1. Jupyter notebooks
After taking Data 8, you must already be quite familiar with navigating Jupyter notebooks. Restarting the kernel,creating new cells, changing cell types is probably second nature to you. You know that double-clicking on markdown cells enables editing, while pressing `shift`+`enter` runs the current cell and selects the cell below. The purpose of this section is not to reteach how to use Jupyter notebooks, but rather help you achieve a potential mastery of Jupyer notebooks, if you choose to.

## 1.1. Edit mode vs. command mode
More likely than not, you have used hotkeys (e.g. `shift`+`enter`) while editing cells in Jupyer notebook. Have you noticed that there are two sets of hotkey bindings depending on whether you are editing a cell?

#### Edit mode
When you see a green border around your cell, you are in edit mode. The hotkeys associated with edit mode assist you with editing and running your code. These include typical editing hotkeys such as `ctrl`+`a`, `ctrl`+`c`,`ctrl`+`z`,`ctrl`+`y` Here are a few more helpful examples:

1. `shift`+`enter` run current cell and select cell below
2. `ctrl`+`enter` run current cell only
3. `tab` indent or help with code completion (will talk about more)
4. `shift`+`tab` dedent
5. `alt`+`drag` vertical text selection and multi-cursor editing 
6. `ctrl`+`shift`+`-` split cell
7. higlight line(s) `ctrl`+`/` toggle comment line(s)
8. `esc` enter command mode

#### Command mode
When you see a grey border with a left blue margin surrounding your cell, you are in command mode. Hotkeys in this mode enable you to quickly use notebook level commands such as inserting new cells, deleting cells, and changing the cell type along with many other features. Here are a some helpful examples:

1. `shift`+`enter` run current cell and select cell below
2. `ctrl`+`enter` only run current cell
3. `d`+`d` delete selected cell
4. `z` undo cell deletion
5. `a` insert cell above
6. `b` insert cell below
7. `y` change cell type to code
8. `m` change cell type to markdown
9. `enter` enter edit mode

You should notice that some commands work in both modes. To access a full list of shortcuts, press `h` while in command mode. Alternatively, click on **Help** in the menu above and then **Keyboard Shortcuts**. `ctrl`+`shit`+`p` also works but it technically opens up the "command pallete" which allows you to search for Jupyter commands.

Even if you are familiar with Jupyter, we strongly encourage you to become proficient with keyboard shortcuts (this will save you time in the future).

#### Note for mac users

`cmd` = `ctrl`

`option` = `alt`

**Question 1.1.1.** Suppose you wrote the code below which consists of two variants of a function. The first is commented out, because you wanted to test which of the two functions work better. You realize that the first was better than the second. Remove the comments from the first function and comment out the second function rather than deleting it (sometimes, it is helpful to have documentation of your old code). You should not be manually inserting and deleting comments.

In [ ]:
# def trueBaller():
#     kyrie = lambda giannis : giannis
#     for i in range(20):
#         if i > 20:
#             return "lebron james"
#         elif len("james harden".split(" ")) == 2:
#             return kyrie("kawhi leonard")
#     return "steph curry"

def trueBaller():
    baller = "lonzo ball"
    def bigBaller(ball):
        while len(ball) > len("vytautas"):
            ball = ball[:-1]
        return ball
    if baller == bigBaller(baller):
        return baller
    return "lavar ball"

**Question 1.1.2.** Suppose you accidentally misplaced the for loop below. The for loop along with everything inside it should be on the same identation level as the outer for loop. You should not be pressing backspace or any other key binding multiple times.

In [ ]:
x = 0
for i in np.arange(5):
    x += 1
    for j in np.arange(5):
        if x > 30:
            x /= 2
        else:
            x += 1
x

**Question 1.1.3.** Python has many built in functions to modify string objects. They are called by first typing your string or the variable referencing your string, adding a dot and the name of the function, and finally closing with parenthesis around the parameters of your function, if any. Here are some examples: 
```python
"HELLO WORLD".lower()
"some string literal".split(" ")
" ".join(["the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"])
```
To look up these many functions, type your string (or the variable) and the dot and press tab. Utilizing this method, try to find a function that can help you capitalize every character in the string below. (Hint: the function to lowercase everything is the first example given).

In [ ]:
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et magna convallis."

In [ ]:
uppercaseText = text
uppercaseText

## 1.2. Advanced code cells

#### Dynamic object information

If you are ever confused about a particular object or a function, you can add a question mark after the object or function and run the cell to display documentation about it. The syntax should be like "obj?" or "obj.foobar?" without the quotes.

**Question 1.2.1.** Run the cells below and see what happens.

In [ ]:
str?

In [ ]:
temp = "hello world"
temp?

In [ ]:
temp.split?

**Question 1.2.2.** Another way you can pull up the documentaion for any function in Jupyter is by typing the function name, then `shift`+`tab` on your keyboard. It is super convenient when you forget the arguments to a function. You can press `tab` multiple times while holding down `shift` to expand the documentation. Try it on the function below:

In [ ]:
np.linspace

## 1.3. Advanced text cells

#### Markdown
If you recall, text cells are written in a format called [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Utilizing only plain text and a simple syntax, it allows you to create section headings, ordered lists, underlines, bolded words, and more. You don't need to learn Markdown, but you might want to since it is somewhat ubiquitous for websites.

Text cells (like this one) can be edited by double-clicking on them. After you edit a text cell, run the cell to confirm any changes. (Try not to delete the instructions of the lab.)

#### Latex
Jupyter's version of Markdown also allows you to write in $\LaTeX$ script to render aesthetic math expressions. For those of you that are already familiar with $\LaTeX$, note that this is a dynamic and slightly different version of $\LaTeX$ in the sense that it is only used to format math expressions, not entire documents. Just type your standard math commands surrounded by dollar signs while in Markdown. Here are a few examples of what $\LaTeX$ can do:

$$ P\left(A \mid B\right) = \frac{P\left(B \mid A\right) \, P\left(A\right)}{P\left(B\right)}  $$
$$ \sum^n_{k=1} e^{-\lambda} \frac{\lambda^k}{k!} $$
$$ \lim\limits_{n \to \infty} \left(1+\frac{1}{n}\right)^n $$

You can learn how to use latex [here](https://www.tug.org/~hvoss/PDF/mathmode.pdf). Here is a list of $\LaTeX$ math [commands](https://reu.dimacs.rutgers.edu/Symbols.pdf).

# 2. Python

Python is the main programming language we'll use in the course. We expect that you've taken Data 8 or an equivalent class so the following sections should not be very difficult for you.

If you need a refresher, please review one or more of the following materials.

- **[Python Tutorial](https://docs.python.org/3.5/tutorial/)**: Introduction to Python from the creators of Python
- **[Composing Programs Chapter 1](http://composingprograms.com/pages/11-getting-started.html)**: This is more of a introduction to programming with Python.
- **[Advanced Crash Course](http://cs231n.github.io/python-numpy-tutorial/)**: A fast crash course which assumes some programming background.

## 2.1. Overview

You should be able to explain the following cells. Run them and make sure you understand what is happening in each.

#### Importing modules

In [37]:
import math
import numpy as np

#### Mathematical Expressions

In [52]:
# This is a comment.
1 - 1

2

In [53]:
# Multipliation, division, and exponentiation.
(2*2) + (1/2) + (4**2)

20.5

In [54]:
# Order of operations matter in Python.
1 + 2*2**3/2

9.0

In [55]:
# Remainder or modulo.
3 % 2

1

In [56]:
# Logs.
math.log(16, 2)

4.0

In [57]:
# More Logs.
math.log(16) / math.log(2)

4.0

#### Output and Printing

In [26]:
"Why didn't this line print?"

print("Hello" + ",", "world!")

"Hello, cell" + " output!"

Hello, world!


'Hello, cell output!'

In [29]:
print(False and True)

False


In [30]:
print(0 and True)

0


In [27]:
print(1 and True or False)

True


#### Comparisons

In [60]:
# This is a numerical comparison
1 < 1

False

In [61]:
1 >= 0

True

In [62]:
0 == 0

True

In [63]:
# Does this work?
1 < 1 + 1 <= 3

True

In [64]:
# What about this?
"aardvark" < "bee" < "cat"

True

#### Variable Assignment

In [66]:
# Creating variables
a = 1
b = 2
a + b

3

In [68]:
# One of the only certainties in the world.
purchase_price = 5
state_tax_rate = 0.075
county_tax_rate = 0.02
city_tax_rate = 0
sales_tax_rate = state_tax_rate + county_tax_rate + city_tax_rate
sales_tax = purchase_price * sales_tax_rate
sales_tax

0.475

#### Control

In [131]:
# If statement
distance = 1.5

if distance >= 2:
    description = "very"
elif height <= 1:
    description = "not"
else:
    description = "kinda"
    
print(f"Alice lives {description} far from campus.")

Alice lives kinda far from campus.


#### Functions

In [107]:
# Calling a function
abs(5-10)

5

In [108]:
# Calling another function
round(10.2)

10

In [109]:
# Defining a function
def add2(x):
    """This docstring explains what this function does: it adds 2 to a number."""
    return x + 2

In [114]:
# Getting help
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [113]:
# Try this
help(add2)

Help on function add2 in module __main__:

add2(x)
    This docstring explains what this function does: it adds 2 to a number.



#### NumPy Arrays

In [69]:
# Initializing an array
my_array = np.array([1, 2, 3, 4, 5])

In [103]:
# Does this create the same array?
np.arange(5)

array([0, 1, 2, 3, 4])

In [105]:
# What about this?
np.arange(1,5)

array([1, 2, 3, 4])

In [106]:
# Remember inclusive start, exclusive stop, and step
np.arange(1,6, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [92]:
# Scalar addition and multiplication.
my_array * 2 + 1

array([ 3,  5,  7,  9, 11])

In [87]:
# Vector addition.
my_array + my_array

array([ 2,  4,  6,  8, 10])

In [93]:
# Vector multiplication.
my_array * my_array

array([ 1,  4,  9, 16, 25])

In [88]:
# The first item.
my_array.item(1)

2

In [90]:
# But indices begin with 0 in python!
my_array.item(0)

1

In [99]:
# Does this work?
my_array.item(my_array.size)

IndexError: index 5 is out of bounds for axis 0 with size 5

## 1.2 Objects / Types
An object in computer science is particular representation of data. In the past you have used very simple objects such as strings and integers. You have also used more complex data structures such as arrays which are collections of other objects. In Python, objects are known as types.

#### Primitives
The most basic representations of data are known as primitives. These include:
-  int, float, complex (numeric types)
-  bool (True, False)
-  str ("hello world")
-  NoneType

#### Mutability
Not all python objects handle changes the same way. Some objects are mutable, meaning they can be altered. Others are immutable; they cannot be changed but rather return new objects when attempting to update. What does this mean when writing python code?

#### Arrays (ndarray)

Something about arrays.

In [ ]:
np.arange(10)

In [ ]:
np.array([1,2,3])

In [ ]:
np.array([1, 'a', None])

In [ ]:
np.arange(10)[1:5]

In [ ]:
exampleArray = np.arange(10)
exampleArray[1:5] = 2
exampleArray

In [ ]:
[1,2,3] + [1,2,3]

In [ ]:
[1,2,3]*2

In [ ]:
np.array([1,2,3]) @ np.array([1,2,3])

In [ ]:
np.array([[1,2,3],[1,2,3]]) @ np.array([[1,2],[1,2],[1,2]])

In [ ]:
np.array([1,2,3])*2

#### Lists
Lists are mutable sequences, typically used to store collections of homogeneous items (where the precise degree of similarity will vary by application). Here is how we can initialize lists:

In [ ]:
# Using square brackets and commas.
[1, 'a', None]

In [ ]:
# Using a list comprehension.
[i for i in np.arange(10)]

In [ ]:
# Using the list intializer.
list(np.arange(10))

In [ ]:
# An empty list.
[]

In [ ]:
# Another empty list.
list()

Lists implement all Python's built-in mutable sequence operations which include slicing and appending items to lists. Let us use the following `exampleList` which has its items correspond to their index number to demonstrate. Notice the differences between lists and arrays.

In [ ]:
# Assigning variable to reference list.
exampleList = list(np.arange(10))
# A copy of exampleList?
exampleList2 = exampleList
# Another copy of exampleList?
exampleList3 = list(exampleList)

In [ ]:
# The list.
print(exampleList)

# Indexing (first item in list).
print(exampleList[0])

# Indexing backwards (first item from the end).
print(exampleList[-1])

# Slicing from item 1 (inclusive) to item 5 (exclusive).
print(exampleList[1:5])

# Slicing from the item.
print(exampleList[1:])

# Slicing up to the third to last item.
print(exampleList[:-3])

# Selecting every other item from a previous slice.
print(exampleList[1:5:2])

# The list backwards.
print(exampleList[::-1])

In [ ]:
# Replacing item 5 (0 indexed) with -5.
exampleList[5] = -5
exampleList

In [ ]:
# Replacing slice of list from item 1 (inclusive) to item 5
# (exclusive) with iterable.
# What will happen if you run this cell multiple times?
exampleList[1:6] = np.arange(4)
exampleList

In [ ]:
# same as s[i:j] = []
del exampleList[0:6]
exampleList

In [ ]:
# Replacing slice of list from item 1 (inclusive) with iterable.
exampleList[1:] = [2]
exampleList

In [ ]:
# What happened to exampleList2?
exampleList2

In [ ]:
# What happened to exampleList3?
exampleList3

#### Ranges

The range type represents an immutable sequence of numbers and is commonly used for looping a specific number of times in for loops.

#### Tuples
Tuples are immutable sequences, typically used to store collections of heterogeneous data (such as the 2-tuples produced by the enumerate() built-in). Tuples are also used for cases where an immutable sequence of homogeneous data is needed (such as allowing storage in a set or dict instance).

#### Dictionaries
A mapping object maps hashable values to arbitrary objects. Mappings are mutable objects.

A dictionary’s keys are almost arbitrary values. Values that are not hashable, that is, values containing lists, dictionaries or other mutable types (that are compared by value rather than by object identity) may not be used as keys. Numeric types used for keys obey the normal rules for numeric comparison: if two numbers compare equal (such as 1 and 1.0) then they can be used interchangeably to index the same dictionary entry. (Note however, that since computers store floating-point numbers as approximations it is usually unwise to use them as dictionary keys.)

Dictionaries can be created by placing a comma-separated list of key: value pairs within braces, for example: {'jack': 4098, 'sjoerd': 4127} or {4098: 'jack', 4127: 'sjoerd'}, or by the dict constructor.

In [ ]:
a = dict(one=1, two=2, three=3)
b = {'one': 1, 'two': 2, 'three': 3}
c = dict(zip(['one', 'two', 'three'], [1, 2, 3]))
d = dict([('two', 2), ('one', 1), ('three', 3)])
e = dict({'three': 3, 'one': 1, 'two': 2})
a == b == c == d == e

# 2. Pandas

Pandas is an open source Python module providing fast, flexible, easy-to-use data structures, and data analysis tools. It is very similar to Data 8's datascience module, but Pandas also includes more complicated features such as row indexes, hierarchical indexes, time series data, missing values, and slicing. 

For R users, Pandas's table provides everything that R’s data.frame provides and much more. 

- Easy handling of missing data (represented as NaN) in floating point as well as non-floating point data
- Size mutability: columns can be inserted and deleted from DataFrame and higher dimensional objects
- Automatic and explicit data alignment: objects can be explicitly aligned to a set of labels, or the user can simply ignore the labels and let Series, DataFrame, etc. automatically align the data for you in computations
- Powerful, flexible group by functionality to perform split-apply-combine operations on data sets, for both aggregating and transforming data
- Make it easy to convert ragged, differently-indexed data in other Python and NumPy data structures into DataFrame objects
- Intelligent label-based slicing, fancy indexing, and subsetting of large data sets
- Intuitive merging and joining data sets
- Flexible reshaping and pivoting of data sets
- Hierarchical labeling of axes (possible to have multiple labels per tick)
- Robust IO tools for loading data from flat files (CSV and delimited), Excel files, databases, and saving / loading data from the ultrafast HDF5 format
- Time series-specific functionality: date range generation and frequency conversion, moving window statistics, moving window linear regressions, date shifting and lagging, etc.

## 2.1. Tables to Dataframes

In this section, we will go over how we can create table like object in Pandas like you would in Datascience.

#### Tables

As you may recall, we intialized a `tbl` object in the datascience module by the following ways:

In [ ]:
# An empty table, usually to extend with data
Table()

In [ ]:
# A table from a data file (e.g. .csv)
Table().read_table(filename)

In [ ]:
# A table with an additional or replaced column
# or columns. name is a string for the name of 
# a column, values is an array.

tbl.with_columns(name, values)

In [ ]:
# A table with an additional or replaced column
# or columns.

tbl.with_columns(n1, v1, n2, v2,...)

#### Dataframes

In pandas, instead of initializing a `tbl` object, we intialize a `dataframe`. You can think of a `dataframe` as you would a `tbl`. Soon, you will learn of the addition features a `dataframe` has.

In [ ]:
# Standard import lines at customarily at beginning of notebook

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# blah blah blah, I am a comment.

df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })

In [ ]:
df2['E'][0]

In [ ]:
df = pd.DataFrame({
    'A': np.arange(100),
    'B': ['Alice' if i%2==0 else 'Eve' for i in np.arange(100)],
    'C': ['Bob' if i%3==0 else 'Adam' for i in np.arange(100)]})
df

In [ ]:
df.groupby(['B','C']).sum()

In [ ]:
df2.axes

## 2.2. Methods

#### Magic commands

In [ ]:
%magic

In [ ]:
%quickref

In [ ]:
import pandas as pd

In [ ]:
str.join?


 They're written in a simple format called [Markdown](http://daringfireball.net/projects/markdown/syntax) to add formatting and section headings.  You don't need to learn Markdown, but you might want to.



In [ ]:
%quickref

In [ ]:
%magic